development: &development
  database: neuron_development
  adapter: mysql2
  host: localhost
  username: root
  password:

test: &test
  database: neuron_test
  adapter: mysql2
  host: localhost
  username: root
  password: